version: '3'

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        volumes:
            - .:/var/www/html
        depends_on:
            - database
        networks:
            - laravel

    database:
        container_name: database
        image: mongo:latest
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: main
        volumes:
            - .docker/mongo:/data/db
        networks:
            - laravel

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - laravel

volumes:
    database:

networks:
    laravel:
